// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/entrar": {
    params: {};
  };
  "/cadastro": {
    params: {};
  };
  "/buscar": {
    params: {};
  };
  "/super": {
    params: {};
  };
  "/destinos/:slug": {
    params: {
      "slug": string;
    };
  };
  "/trilhas/:slug": {
    params: {
      "slug": string;
    };
  };
  "/agencias/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin/entrar": {
    params: {};
  };
  "/admin/setup": {
    params: {};
  };
  "/admin/mp-callback": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/passeios": {
    params: {};
  };
  "/admin/passeios/novo": {
    params: {};
  };
  "/admin/passeios/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/reservas": {
    params: {};
  };
  "/admin/reservas/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/clientes": {
    params: {};
  };
  "/admin/configuracoes": {
    params: {};
  };
  "/admin/checkin/:tourId": {
    params: {
      "tourId": string;
    };
  };
  "/passeios/:slug": {
    params: {
      "slug": string;
    };
  };
  "/reserva/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ticket/:token": {
    params: {
      "token": string;
    };
  };
  "/cliente/entrar": {
    params: {};
  };
  "/cliente/cadastro": {
    params: {};
  };
  "/cliente/minhas-reservas": {
    params: {};
  };
  "/webhooks/mercadopago": {
    params: {};
  };
  "/api/criar-preferencia": {
    params: {};
  };
  "/pagamento/resultado": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/entrar" | "/cadastro" | "/buscar" | "/super" | "/destinos/:slug" | "/trilhas/:slug" | "/agencias/:slug" | "/admin/entrar" | "/admin/setup" | "/admin/mp-callback" | "/admin" | "/admin/passeios" | "/admin/passeios/novo" | "/admin/passeios/:id" | "/admin/reservas" | "/admin/reservas/:id" | "/admin/clientes" | "/admin/configuracoes" | "/admin/checkin/:tourId" | "/passeios/:slug" | "/reserva/:slug" | "/ticket/:token" | "/cliente/entrar" | "/cliente/cadastro" | "/cliente/minhas-reservas" | "/webhooks/mercadopago" | "/api/criar-preferencia" | "/pagamento/resultado";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/entrar.tsx": {
    id: "routes/entrar";
    page: "/entrar";
  };
  "routes/cadastro.tsx": {
    id: "routes/cadastro";
    page: "/cadastro";
  };
  "routes/buscar.tsx": {
    id: "routes/buscar";
    page: "/buscar";
  };
  "routes/super.tsx": {
    id: "routes/super";
    page: "/super";
  };
  "routes/destino.tsx": {
    id: "routes/destino";
    page: "/destinos/:slug";
  };
  "routes/trilha.tsx": {
    id: "routes/trilha";
    page: "/trilhas/:slug";
  };
  "routes/agencia.tsx": {
    id: "routes/agencia";
    page: "/agencias/:slug";
  };
  "routes/admin.entrar.tsx": {
    id: "routes/admin.entrar";
    page: "/admin/entrar";
  };
  "routes/admin.setup.tsx": {
    id: "routes/admin.setup";
    page: "/admin/setup";
  };
  "routes/admin.mp-callback.tsx": {
    id: "routes/admin.mp-callback";
    page: "/admin/mp-callback";
  };
  "routes/admin.layout.tsx": {
    id: "routes/admin.layout";
    page: "/admin" | "/admin/passeios" | "/admin/passeios/novo" | "/admin/passeios/:id" | "/admin/reservas" | "/admin/reservas/:id" | "/admin/clientes" | "/admin/configuracoes" | "/admin/checkin/:tourId";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.passeios.tsx": {
    id: "routes/admin.passeios";
    page: "/admin/passeios";
  };
  "routes/admin.passeios.novo.tsx": {
    id: "routes/admin.passeios.novo";
    page: "/admin/passeios/novo";
  };
  "routes/admin.passeios.$id.tsx": {
    id: "routes/admin.passeios.$id";
    page: "/admin/passeios/:id";
  };
  "routes/admin.reservas.tsx": {
    id: "routes/admin.reservas";
    page: "/admin/reservas";
  };
  "routes/admin.reservas.$id.tsx": {
    id: "routes/admin.reservas.$id";
    page: "/admin/reservas/:id";
  };
  "routes/admin.clientes.tsx": {
    id: "routes/admin.clientes";
    page: "/admin/clientes";
  };
  "routes/admin.configuracoes.tsx": {
    id: "routes/admin.configuracoes";
    page: "/admin/configuracoes";
  };
  "routes/admin.checkin.$tourId.tsx": {
    id: "routes/admin.checkin.$tourId";
    page: "/admin/checkin/:tourId";
  };
  "routes/passeio.tsx": {
    id: "routes/passeio";
    page: "/passeios/:slug";
  };
  "routes/reserva-status.tsx": {
    id: "routes/reserva-status";
    page: "/reserva/:slug";
  };
  "routes/ticket.tsx": {
    id: "routes/ticket";
    page: "/ticket/:token";
  };
  "routes/cliente.entrar.tsx": {
    id: "routes/cliente.entrar";
    page: "/cliente/entrar";
  };
  "routes/cliente.cadastro.tsx": {
    id: "routes/cliente.cadastro";
    page: "/cliente/cadastro";
  };
  "routes/cliente.reservas.tsx": {
    id: "routes/cliente.reservas";
    page: "/cliente/minhas-reservas";
  };
  "routes/webhooks.mercadopago.tsx": {
    id: "routes/webhooks.mercadopago";
    page: "/webhooks/mercadopago";
  };
  "routes/api.criar-preferencia.tsx": {
    id: "routes/api.criar-preferencia";
    page: "/api/criar-preferencia";
  };
  "routes/pagamento.resultado.tsx": {
    id: "routes/pagamento.resultado";
    page: "/pagamento/resultado";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/entrar": typeof import("./app/routes/entrar.tsx");
  "routes/cadastro": typeof import("./app/routes/cadastro.tsx");
  "routes/buscar": typeof import("./app/routes/buscar.tsx");
  "routes/super": typeof import("./app/routes/super.tsx");
  "routes/destino": typeof import("./app/routes/destino.tsx");
  "routes/trilha": typeof import("./app/routes/trilha.tsx");
  "routes/agencia": typeof import("./app/routes/agencia.tsx");
  "routes/admin.entrar": typeof import("./app/routes/admin.entrar.tsx");
  "routes/admin.setup": typeof import("./app/routes/admin.setup.tsx");
  "routes/admin.mp-callback": typeof import("./app/routes/admin.mp-callback.tsx");
  "routes/admin.layout": typeof import("./app/routes/admin.layout.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.passeios": typeof import("./app/routes/admin.passeios.tsx");
  "routes/admin.passeios.novo": typeof import("./app/routes/admin.passeios.novo.tsx");
  "routes/admin.passeios.$id": typeof import("./app/routes/admin.passeios.$id.tsx");
  "routes/admin.reservas": typeof import("./app/routes/admin.reservas.tsx");
  "routes/admin.reservas.$id": typeof import("./app/routes/admin.reservas.$id.tsx");
  "routes/admin.clientes": typeof import("./app/routes/admin.clientes.tsx");
  "routes/admin.configuracoes": typeof import("./app/routes/admin.configuracoes.tsx");
  "routes/admin.checkin.$tourId": typeof import("./app/routes/admin.checkin.$tourId.tsx");
  "routes/passeio": typeof import("./app/routes/passeio.tsx");
  "routes/reserva-status": typeof import("./app/routes/reserva-status.tsx");
  "routes/ticket": typeof import("./app/routes/ticket.tsx");
  "routes/cliente.entrar": typeof import("./app/routes/cliente.entrar.tsx");
  "routes/cliente.cadastro": typeof import("./app/routes/cliente.cadastro.tsx");
  "routes/cliente.reservas": typeof import("./app/routes/cliente.reservas.tsx");
  "routes/webhooks.mercadopago": typeof import("./app/routes/webhooks.mercadopago.tsx");
  "routes/api.criar-preferencia": typeof import("./app/routes/api.criar-preferencia.tsx");
  "routes/pagamento.resultado": typeof import("./app/routes/pagamento.resultado.tsx");
};